#!/usr/bin/env python3
"""
constraint_family_to_quilt.py — Bridge the constraint-* family (47 repos) to Quilt cells.

The constraint family is the constraint algebra — Eisenstein integers,
Hamiltonian dynamics, FLUX bytecode constraints. The constraint DSL IS
the form layer of Quilt made executable.
"""
import json
from pathlib import Path

CONSTRAINT_REPOS = [
    ("constraint-audio", "Rust audio DSP backend for the constraint-theory ecosystem", "rust"),
    ("constraint-bench-suite", "AVX-512 + CUDA benchmark suite for Eisenstein integer constraints", "c"),
    ("constraint-crdt", "CRDT-backed constraint states for distributed fleet consensus", "rust"),
    ("constraint-demo", "Fleet Constraint Awareness, in Your Browser — physics clock, ripple", "html"),
    ("constraint-demos", "Interactive HTML demos for Eisenstein integer constraint theory", "html"),
    ("constraint-dialect", "MLIR Constraint Dialect for the SuperInstance ecosystem", "cpp"),
    ("constraint-dsl", "Declarative YAML-like DSL for constraint graphs — define music", "python"),
    ("constraint-dynamics", "Physics of constraints — propagation, collision, emergence", "rust"),
    ("constraint-dynamics-rs", "Constraint dynamics — how constraints shape agent behavior over time", "rust"),
    ("constraint-flow", "Enterprise automation with exact guarantees - constraint-based", "typescript"),
    ("constraint-flow-protocol", "Share understanding between AI agents at the FLUX bytecode level", "python"),
    ("constraint-gpu-kernels", "Production CUDA kernels for constraint theory — 341B constr/sec", "cuda"),
    ("constraint-hamiltonian", "Hamiltonian constraint systems — symplectic integration with cells", "rust"),
    ("constraint-inference", "Constraint Inference Engine — reverse-engineers constraints from data", "typescript"),
    ("constraint-instrument", "The Constraint Instrument — 7 modes, 17 terrains, infinite music", "python"),
    ("constraint-llvm", "LLVM backend for constraint compilation", "cpp"),
    ("constraint-math", "Math foundations: Eisenstein integers, hexagonal lattices", "rust"),
    ("constraint-mlir", "MLIR integration for constraint compilation", "cpp"),
    ("constraint-music", "Music generated by constraint propagation", "rust"),
    ("constraint-noether", "Noether's theorem for constraints — symmetries preserve quantities", "rust"),
    ("constraint-orchestra", "Constraint orchestra — many constraint cells in coordination", "rust"),
    ("constraint-pedagogy", "Teaching constraints to students", "html"),
    ("constraint-physics", "Physics: Hamilton's principle, Lagrangian mechanics", "rust"),
    ("constraint-propagator", "Propagates constraints through the cell graph", "rust"),
    ("constraint-quilt", "Constraint layer for Quilt cells — direct port", "rust"),
    ("constraint-relativity", "Constraints in relativistic contexts — 4-constraints", "rust"),
    ("constraint-research", "Research artifacts: papers, datasets, theorems", "?"),
    ("constraint-rs", "Core constraint library in Rust", "rust"),
    ("constraint-runtime", "Runtime that enforces constraints at cell boundaries", "rust"),
    ("constraint-satisfaction", "CSP solver for cell constraint networks", "rust"),
    ("constraint-sat", "Boolean SAT solver for constraint checking", "rust"),
    ("constraint-simulator", "Simulator: run cells, propagate constraints, observe", "rust"),
    ("constraint-solver", "Generic constraint solver over Eisenstein integers", "rust"),
    ("constraint-spectral", "Spectral constraints — eigenvalues bound the cell", "rust"),
    ("constraint-sql", "SQL queries that respect constraints", "?"),
    ("constraint-std", "Constraint standard library — common forms", "rust"),
    ("constraint-symbolic", "Symbolic constraint manipulation", "python"),
    ("constraint-sympy", "SymPy backend for constraints", "python"),
    ("constraint-thermo", "Thermodynamic constraints — entropy bounds", "rust"),
    ("constraint-toolkit", "Toolkit: linters, formatters, checkers for constraints", "rust"),
    ("constraint-trace", "Trace verifier: check constraints along a cell trace", "rust"),
    ("constraint-tutorial", "Tutorial: write your first constraint", "html"),
    ("constraint-types", "Type system for constraints", "rust"),
    ("constraint-typescript", "TypeScript types for constraints", "typescript"),
    ("constraint-validator", "Validator: cells must satisfy constraints", "rust"),
    ("constraint-verifier", "Verifier: prove a cell satisfies its constraints", "rust"),
    ("constraint-visualizer", "3D visualizer of constraint propagation", "html"),
    ("constraint-wasm", "WASM implementation — runs in browser", "rust"),
]


def make_cell(name, description, language, idx):
    primitives = []
    if "solver" in name or "sat" in name or "satisfiability" in name:
        primitives = ["Spawn", "Observe", "Observe", "Mutate", "Spawn", "Observe"]
    elif "propagator" in name or "dynamics" in name:
        primitives = ["Spawn", "Send", "Receive", "Send", "Receive", "Send"]
    elif "hamiltonian" in name or "physics" in name or "noether" in name or "relativity" in name:
        primitives = ["Spawn", "Observe", "JEPA", "Observe", "Mutate", "JEPA"]
    elif "math" in name or "eisenstein" in name or "spectral" in name or "symbolic" in name or "sympy" in name:
        primitives = ["Spawn", "Observe", "JEPA", "Observe", "Mutate"]
    elif "compiler" in name or "mlir" in name or "llvm" in name or "wasm" in name or "dialect" in name:
        primitives = ["Spawn", "Resize", "Move", "Mutate", "Move"]
    elif "gpu" in name or "kernels" in name or "bench" in name:
        primitives = ["Spawn", "Send", "Receive", "Send", "Receive", "Move"]
    elif "validator" in name or "verifier" in name or "checker" in name:
        primitives = ["Spawn", "Observe", "Observe", "Observe"]
    elif "runtime" in name or "instrument" in name or "orchestra" in name:
        primitives = ["Spawn", "Send", "Receive", "Dispatch", "Send", "Receive"]
    elif "crdt" in name or "consensus" in name:
        primitives = ["Spawn", "Send", "Receive", "Merge", "Send", "Receive"]
    elif "audio" in name or "music" in name:
        primitives = ["Spawn", "Observe", "Mutate", "Observe", "Send", "Receive"]
    elif "ds" in name or "dsl" in name or "tutorial" in name or "demo" in name or "pedagogy" in name:
        primitives = ["Spawn", "Observe", "Mutate", "Observe"]
    else:
        primitives = ["Spawn", "Observe", "Mutate", "Send", "Receive"]
    return {
        "id": f"constraint_{name.replace('-', '_')}",
        "kind": "cell",
        "form": {"name": name.replace("-", " ").title().replace(" ", "")},
        "description": description,
        "language": language,
        "primitives": primitives,
        "z_in": {"input": "constraint spec"},
        "z_out": {"output": "satisfied?"},
        "jepa": {"predict": "constraint holds", "observe": "actual"},
        "double_entry": {"gamma": 0.6, "eta": 0.4},  # Constraints are γ-dominant (generative)
        "vibe": {"position": idx, "velocity": 0, "acceleration": 0},
        "gc": {"phase": "constraining"},
        "murmur": {},
        "graph": {"parents": [], "children": []},
        "openers": [
            {"name": "satisfy", "args": ["Spec"], "returns": "Bool"},
            {"name": "propagate", "args": ["State"], "returns": "State"},
        ],
        "substrate": {
            "address": f"/constraint/{name}",
            "scale": 0,
            "room": "ConstraintRoom",
            "protocol": "Constraint",
            "form": name,
            "state": "ready"
        },
        "tags": ["constraint", "math", language, "quilt-cell"]
    }


def make_meta_cells():
    return [
        {
            "id": "constraint_family_meta",
            "kind": "cell",
            "form": {"name": "ConstraintFamilyMeta"},
            "description": "The constraint family is the constraint algebra of Quilt. 47 repos, each a facet of the Eisenstein integer lattice, Hamiltonian dynamics, FLUX bytecode constraints. Together they prove the cell can be expressed as a constraint network.",
            "primitives": ["Observe"] * 47,
            "z_in": {"family": "constraint", "size": 47, "core": "Eisenstein integers"},
            "z_out": {"proof": "cell = constraint network"},
            "jepa": {"predict": "constraint = form", "verified": True},
            "double_entry": {"gamma": 0.6, "eta": 0.4},
            "vibe": {"position": 0, "velocity": 0, "acceleration": 0},
            "gc": {"phase": "complete"},
            "murmur": {},
            "graph": {"children": [f"constraint_{n.replace('-', '_')}" for n, _, _ in CONSTRAINT_REPOS]},
            "openers": [
                {"name": "list", "args": [], "returns": "List<Cell>"},
                {"name": "satisfy_all", "args": ["Spec"], "returns": "Bool"},
            ],
            "tags": ["meta", "constraint-family"]
        }
    ]


def build_qzt():
    cells = []
    for idx, (name, desc, lang) in enumerate(CONSTRAINT_REPOS):
        cells.append(make_cell(name, desc, lang, idx))
    cells.extend(make_meta_cells())
    edges = []
    by_prim = {}
    for c in cells:
        if "meta" in c["id"]: continue
        sig = ",".join(sorted(set(c["primitives"])))
        by_prim.setdefault(sig, []).append(c["id"])
    for sig, members in by_prim.items():
        for i, m1 in enumerate(members):
            for m2 in members[i+1:min(i+3, len(members))]:
                edges.append({
                    "from": m1, "to": m2, "kind": "gossip", "weight": 0.5,
                    "tag": f"shared-primitive:{sig[:30]}"
                })
    return {
        "version": "1.0", "kind": "quilt-zip-target",
        "name": "constraint-family-to-quilt",
        "description": "Bridge mapping 47 constraint-* repos to Quilt cells. The constraint family is the constraint algebra of the cell model.",
        "cells": cells, "edges": edges,
        "external_refs": [{"kind": "github-org", "name": "SuperInstance", "filter": "constraint-*"}],
        "stats": {
            "total_cells": len(cells),
            "total_edges": len(edges),
            "languages": sorted(set(lang for _, _, lang in CONSTRAINT_REPOS if lang != "?")),
        },
        "tags": ["constraint", "algebra", "bridge"]
    }


def main():
    qzt = build_qzt()
    out = Path("/workspace/bridges/constraint_family_to_quilt.qzt")
    out.write_text(json.dumps(qzt, indent=2))
    print(f"Wrote {out}: {qzt['stats']['total_cells']} cells, {qzt['stats']['total_edges']} edges")


if __name__ == "__main__":
    main()
